### ISSUE TITLE
Split screen selection 1 pixel off

### ISSUE THREAD

**Issue by jellewie** [kmisiunas/sweeper-craft#11]
The selection of the play fiets blocks 1 pixel of in hengst. See screenshot 

![screenshot_20160830-210519](https://cloud.githubusercontent.com/assets/1545223/18103531/5bc8989a-6ef7-11e6-9b37-c06567bcac4f.png)

**Comment by kmisiunas** [comment]
Curious. Is the touch calibration reset?

**Comment by kmisiunas** [comment]
This was caused by two deep problems that were partially cancelling each other. 

First, the touch position was returned from the top left corner of the device. The app was designed for top right corner of the app. 

Second, this was partly canceled by a math typo in screen position algorithm, thus making the problem really small for most phones but not tablets. 

Fix:

```
val posOfView = new Array[Int](2)
container.getLocationOnScreen( posOfView )

def x: Int = event.getX.toInt - posOfView(0) // adjust for screen elements
def y: Int = event.getY.toInt - posOfView(1) + calibrationY
```
